id: segment_introduction
learningObjectives: 
- Learn what Segment is and how it works
hints:
- "Sign up here: https://app.segment.com/signup"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: Ben
      messages:
      - text: "Hey there! I'm Ben, your Segment guide. I'll be helping you through this quest. Let's get started!"
      - text: "Segment is a customer data platform that helps you collect, unify, and send customer data to hundreds of tools and destinations, such as Google Analytics, Mixpanel, and Salesforce."
      - text: "It's a powerful tool that can help you unlock powerful insights, automate workflows, and drive growth and retention for your business."
      - text: "First, you'll need to create a Segment account. [You can do that here](https://app.segment.com/signup)"
      - text: "Once you've created your account, :instruction[come back here and let me know when you're ready to continue.]"
trigger:
  type: user_message
  params: 
    person: Ben
  flowNode:
    if:
      conditions:
      - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
        - actionId: bot_message
          params:
            person: Ben
            messages:
            - text: "Great! Now that you have a Segment account, let's integrate it with our website."
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: Ben
            messages:
            - text: "I'm here, just let me know when you're ready to continue."
